// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/defstream/go-kickable/service/micro/proto/cani.proto

/*
Package cani is a generated protocol buffer package.

It is generated from these files:
	github.com/defstream/go-kickable/service/micro/proto/cani.proto

It has these top-level messages:
	CanIKickRequest
	CanIKickResponse
*/
package cani

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CanIKickRequest struct {
	It string `protobuf:"bytes,1,opt,name=it" json:"it,omitempty"`
}

func (m *CanIKickRequest) Reset()                    { *m = CanIKickRequest{} }
func (m *CanIKickRequest) String() string            { return proto.CompactTextString(m) }
func (*CanIKickRequest) ProtoMessage()               {}
func (*CanIKickRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CanIKickRequest) GetIt() string {
	if m != nil {
		return m.It
	}
	return ""
}

type CanIKickResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *CanIKickResponse) Reset()                    { *m = CanIKickResponse{} }
func (m *CanIKickResponse) String() string            { return proto.CompactTextString(m) }
func (*CanIKickResponse) ProtoMessage()               {}
func (*CanIKickResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CanIKickResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*CanIKickRequest)(nil), "CanIKickRequest")
	proto.RegisterType((*CanIKickResponse)(nil), "CanIKickResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Kickable service

type KickableClient interface {
	CanIKick(ctx context.Context, in *CanIKickRequest, opts ...client.CallOption) (*CanIKickResponse, error)
}

type kickableClient struct {
	c           client.Client
	serviceName string
}

func NewKickableClient(serviceName string, c client.Client) KickableClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "kickable"
	}
	return &kickableClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *kickableClient) CanIKick(ctx context.Context, in *CanIKickRequest, opts ...client.CallOption) (*CanIKickResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Kickable.CanIKick", in)
	out := new(CanIKickResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kickable service

type KickableHandler interface {
	CanIKick(context.Context, *CanIKickRequest, *CanIKickResponse) error
}

func RegisterKickableHandler(s server.Server, hdlr KickableHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Kickable{hdlr}, opts...))
}

type Kickable struct {
	KickableHandler
}

func (h *Kickable) CanIKick(ctx context.Context, in *CanIKickRequest, out *CanIKickResponse) error {
	return h.KickableHandler.CanIKick(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/defstream/go-kickable/service/micro/proto/cani.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x40, 0x85, 0xc1, 0xe0, 0x0d, 0x8a, 0x9d, 0x0c, 0x93, 0x32, 0xb9, 0xd8, 0x46, 0x9d, 0x8d,
	0x83, 0x93, 0x61, 0xe3, 0x0f, 0x4a, 0x3d, 0xf1, 0x82, 0x50, 0x6c, 0x0f, 0xbf, 0xdf, 0x84, 0xa0,
	0x26, 0x6c, 0xef, 0x92, 0x77, 0xf7, 0x0e, 0xce, 0x25, 0xf1, 0xa3, 0x2b, 0xa4, 0xb1, 0xb5, 0xba,
	0xe1, 0xdd, 0xb3, 0x43, 0x5d, 0xab, 0xd2, 0xee, 0x2a, 0x32, 0x95, 0x2e, 0x9e, 0xa8, 0x3c, 0xba,
	0x37, 0x19, 0x54, 0x35, 0x19, 0x67, 0x55, 0xeb, 0x2c, 0x5b, 0x65, 0x74, 0x43, 0xb2, 0xc7, 0x74,
	0x03, 0x8b, 0x8b, 0x6e, 0xae, 0x19, 0x99, 0x2a, 0xc7, 0x57, 0x87, 0x9e, 0xc5, 0x1c, 0x42, 0xe2,
	0x55, 0xb0, 0x0e, 0xb6, 0xb3, 0x3c, 0x24, 0x4e, 0x25, 0xc4, 0x7f, 0xc5, 0xb7, 0xb6, 0xf1, 0x28,
	0x12, 0x88, 0xdc, 0xc0, 0x83, 0xf9, 0x9b, 0x0f, 0x27, 0x88, 0xb2, 0xa1, 0x2e, 0xf6, 0x10, 0x7d,
	0x77, 0x45, 0x2c, 0x47, 0xa5, 0x64, 0x29, 0xc7, 0x87, 0xd3, 0x49, 0x31, 0xed, 0x1f, 0x3b, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x9d, 0x00, 0xa2, 0xdb, 0x00, 0x00, 0x00,
}
